// ==UserScript==
// @name         仙境传说 · 无限道场（独立脚本）
// @namespace    dsh.ro-infinite-dojo
// @version      1.1.0
// @updateURL    https://raw.githubusercontent.com/Keeee1th/Lro-user-scripts/main/ro-infinite-dojo.user.js
// @downloadURL  https://raw.githubusercontent.com/Keeee1th/Lro-user-scripts/main/ro-infinite-dojo.user.js
// @description  通过 RO 助手 protocol 1 API 安全运行无限道场。
// @match        http://post.lastro.cn/ro/api.html*
// @match        https://post.lastro.cn/ro/api.html*
// @match        http://post.lastro.cn/ro/api-old.html*
// @match        https://post.lastro.cn/ro/api-old.html*
// @match        http://game.lastro.cn/ro/api.html*
// @match        https://game.lastro.cn/ro/api.html*
// @match        http://127.0.0.1:8971/client/api.html*
// @match        http://localhost:8971/client/api.html*
// @run-at       document-idle
// @grant        none
// ==/UserScript==
(function(){"use strict";
var PROTOCOL=1,KEY="dsh-ro-infinite-dojo-v1",OLD="dsh-ro-challenge-v1",cfg=load(),run={on:false,owner:"dojo-"+Math.random().toString(36).slice(2)+Date.now().toString(36),generation:0,round:0,remaining:null,lastMenu:"",lastNotice:"",lastNoticeAt:0,timer:null,phase:"等待助手",npc:null,lastFly:0},BUNDLED="道馆已并入主脚本，本脚本可卸载";
function load(){var d={difficulty:"basic",stop100:true,fly:false,emergency:false,migrated:false},v;try{v=JSON.parse(localStorage.getItem(KEY)||"null");if(v&&typeof v==="object")Object.assign(d,v);}catch(e){}if(!d.migrated){try{v=JSON.parse(localStorage.getItem(OLD)||"null");if(v&&typeof v==="object"){if(/^(basic|middle|advanced)$/.test(v.difficulty))d.difficulty=v.difficulty;d.stop100=v.stop100!==false;d.fly=v.flyOn===true;d.emergency=v.emergencyFly===true;}}catch(e2){}d.migrated=true;save(d);}return d;}
function save(v){try{localStorage.setItem(KEY,JSON.stringify(v||cfg));}catch(e){}}
function hasDojo(a){var c=a&&typeof a.capabilities==="function"&&a.capabilities();return !!(c&&Array.isArray(c.modules)&&c.modules.indexOf("dojo")>=0);}
function api(){try{var raw=window.__DSH_RO_ASSIST_API__,a=raw&&typeof raw.handshake==="function"&&raw.handshake({protocol:PROTOCOL,client:"ro-infinite-dojo"}),need=["capabilities","ready","snapshot","acquire","release","contactNpc","walkTo","chooseMenu","requestBattle","setArrowTarget","clearArrowTarget","requestFly"],c=a&&a.capabilities();if(!a||a.protocol!==PROTOCOL||!c||c.protocol!==PROTOCOL||c.arrowRules!==true||!Array.isArray(c.scopes)||need.some(function(k){return typeof a[k]!=="function";})||["dojo","battle","movement","dialog","arrow","fly"].some(function(k){return c.scopes.indexOf(k)<0;}))return null;return a;}catch(e){return null;}}
function norm(s){return String(s||"").replace(/\^[0-9a-f]{6}/gi,"").replace(/<[^>]*>/g," ").replace(/[０-９]/g,function(c){return String.fromCharCode(c.charCodeAt(0)-65248);}).replace(/達/g,"达").replace(/貓/g,"猫").replace(/\s+/g," ").trim();}
function notice(raw){if(!run.on)return;var s=norm(raw),now=Date.now(),m;if(!s||(s===run.lastNotice&&now-run.lastNoticeAt<2500))return;run.lastNotice=s;run.lastNoticeAt=now;m=s.match(/第\s*(\d+)\s*[轮层波]/);if(m)run.round=Math.max(run.round,Number(m[1]));m=s.match(/(?:还剩|剩余)\s*[:：]?\s*(\d+)/);if(m)run.remaining=Number(m[1]);m=s.match(/(?:完成|通过)\s*第?\s*(\d+)\s*[轮层波]|第\s*(\d+)\s*[轮层波]\s*(?:完成|结束|通过)/);if(m){run.round=Math.max(run.round,Number(m[1]||m[2]));if(cfg.stop100&&run.round>=100)return stop("第100轮领奖前暂停");run.phase="本轮完成，等待领奖菜单";}render();}
function choose(a,s){var m=s.menu;if(!s.dialogOpen){run.lastMenu="";return false;}if(!m||!m.naid||!Array.isArray(m.items)||!m.items.length||!m.fingerprint)return false;if(m.fingerprint===run.lastMenu)return true;var re=run.phase.indexOf("领奖")>=0?/领取奖励|领奖/:({basic:/初级/,middle:/中级/,advanced:/高级/}[cfg.difficulty]),hits=[];m.items.forEach(function(x,i){if(re.test(norm(x)))hits.push(i);});if(!hits.length&&run.phase.indexOf("领奖")<0)m.items.forEach(function(x,i){if(/继续挑战|开始挑战|进入挑战/.test(norm(x)))hits.push(i);});if(hits.length!==1){run.phase="菜单不唯一，请手动选择";return true;}run.lastMenu=m.fingerprint;var r=a.chooseMenu(run.owner,{naid:m.naid,index:hits[0],fingerprint:m.fingerprint});if(!r||!r.ok)run.phase="菜单提交失败";return true;}
function npcs(s){return(s.npcs||[]).filter(function(n){return/^(喵达人|猫达人|白猫|白猫达人)$/.test(norm(n.name).replace(/\s/g,""));});}
function contact(a,s,now){var list=npcs(s);if(!run.npc)run.npc={gid:list.length===1?list[0].gid:0,firstAt:now,lastAt:0,walked:false};if(now-run.npc.firstAt>=30000)return stop("寻找 NPC 超过30秒，已停止");if(list.length>1){run.phase="NPC 别名不唯一，请手动靠近";return;}if(list.length===1){var n=list[0];if(run.npc.gid!==n.gid)run.npc={gid:n.gid,firstAt:now,lastAt:0,walked:false};if(now-run.npc.lastAt>=1000){a.contactNpc(run.owner,n.gid);run.npc.lastAt=now;}if(now-run.npc.firstAt>=8000&&!run.npc.walked&&n.position){a.walkTo(run.owner,{x:Math.round(n.position[0]),y:Math.round(n.position[1])});run.npc.walked=true;}run.phase="接触道场 NPC";}else if(now-run.npc.firstAt>=8000&&!run.npc.walked){a.walkTo(run.owner,{x:99,y:107});run.npc.walked=true;run.phase="前往 NPC 候选坐标";}else run.phase="寻找道场 NPC";}
function tick(g){if(!run.on||g!==run.generation)return;var a=api(),s=a&&a.snapshot(run.owner),now=Date.now();if(!a||!s||!s.ready)return stop("助手 API 缺失或未就绪");if(choose(a,s)||s.dialogOpen)return render();var t=(s.mobs||[]).filter(function(m){return!m.dead&&m.mid;})[0];if(t){run.npc=null;var ar=a.setArrowTarget(run.owner,{mid:t.mid,gid:t.gid}),fresh=a.snapshot(run.owner),match=fresh&&fresh.arrow&&fresh.arrow.target&&fresh.arrow.target.mid===t.mid&&fresh.arrow.target.gid===t.gid,allowed=cfg.difficulty==="basic"&&fresh&&fresh.arrow&&fresh.arrow.enabled===false||fresh&&fresh.arrow&&fresh.arrow.enabled===true&&fresh.arrow.ready===true&&fresh.arrow.blocked===false&&match;run.phase=allowed?"战斗中":"等待换箭就绪";a.requestBattle(run.owner,!!allowed);if(cfg.emergency&&cfg.difficulty!=="basic"&&s.player&&s.player.maxHp>0&&s.player.hp/s.player.maxHp<.7&&now-run.lastFly>3000){run.lastFly=now;a.requestFly(run.owner,{reason:"道场低血量"});}}else{a.clearArrowTarget(run.owner);if(cfg.fly&&s.inDojoMap&&run.remaining>0&&now-run.lastFly>3000){run.lastFly=now;a.requestFly(run.owner,{reason:"道场无怪且仍有剩余"});}contact(a,s,now);}render();}
function start(){var a=api();if(hasDojo(a))return stop(BUNDLED);if(!a||!a.ready())return stop("缺少兼容的 RO助手 API，功能已禁用");var r=a.acquire(run.owner,["dojo","battle","movement","dialog","arrow","fly"]);if(!r||!r.ok)return stop(r&&r.error||"助手正被其他流程占用");run.on=true;run.generation++;run.round=0;run.remaining=null;run.lastMenu="";run.npc=null;run.lastFly=0;run.phase="启动中";run.timer=setInterval(function(){tick(run.generation);},250);tick(run.generation);}
function stop(reason){var a=api();run.on=false;run.generation++;if(run.timer)clearInterval(run.timer);run.timer=null;if(a&&!hasDojo(a)){try{a.clearArrowTarget(run.owner);a.release(run.owner);}catch(e){}}run.npc=null;run.phase=reason||"已停止";render();}
var p=document.createElement("div");p.id="dsh-dojo-panel";p.style.cssText="position:fixed;left:14px;bottom:14px;z-index:2147483645;width:260px;padding:8px;color:#eaf4ff;background:#192332ef;border:1px solid #8194ad;border-radius:7px;font:12px sans-serif";p.innerHTML='<b>无限道场 · API 模式</b><div><select data-diff><option value="basic">初级</option><option value="middle">中级</option><option value="advanced">高级</option></select> <button data-start>开始</button> <button data-stop>停止</button></div><label><input data-stop100 type="checkbox">100轮领奖前暂停</label><br><label><input data-fly type="checkbox">道场无怪时飞行</label><br><label><input data-emergency type="checkbox">中高级 HP&lt;70%紧急飞行</label><pre data-state></pre><small>换箭由助手配置；不含技能、邮件、push、清包、巡逻。</small>';document.documentElement.appendChild(p);
function q(s){return p.querySelector(s);}function render(){var a=api(),b=hasDojo(a);if(b)run.phase=BUNDLED;q("[data-state]").textContent=run.phase+"\n轮次："+(run.round||"—")+"　剩余："+(run.remaining==null?"—":run.remaining);q("[data-start]").disabled=run.on||b||!a;q("[data-stop]").disabled=!run.on;}q("[data-diff]").value=cfg.difficulty;q("[data-stop100]").checked=cfg.stop100;q("[data-fly]").checked=cfg.fly;q("[data-emergency]").checked=cfg.emergency;p.onchange=function(){cfg.difficulty=q("[data-diff]").value;cfg.stop100=q("[data-stop100]").checked;cfg.fly=q("[data-fly]").checked;cfg.emergency=q("[data-emergency]").checked;save();};q("[data-start]").onclick=start;q("[data-stop]").onclick=function(){stop();};
window.addEventListener("dsh-ro-assist-ready",render);window.addEventListener("dsh-ro-assist-notice",function(e){notice(e.detail&&(e.detail.text||e.detail.message));});window.addEventListener("pagehide",function(){stop("页面离开");});setInterval(render,1000);render();
})();
